Exchanging an authorization code for an access token needs no client_secret
aliev/aioauth pull request #74
Opened 2023-03-20 17:31 UTC by tdg5

It could be that I'm doing something wrong, but if I attempt to exchange an authorization code for an access token and I don't supply some kind of dummy `client_secret`, then I get an `InvalidClientError`. If I supply a blank `client_secret`, I don't have a problem.

Relevant stacktrace is:
```
  File ".../aioauth/server.py", line 256, in create_token_response
    client_id, client_secret = self.get_client_credentials(request)
  File ".../aioauth/server.py", line 216, in get_client_credentials
    raise InvalidClientError[TRequest](
```

I think the code I've suggested solves the problem, but I'm open to other ideas if you prefer a different approach. I don't love that it hardcodes a check for `request.post.grant_type == "client_credentials"` because it makes the library harder to extend with custom grant types, but that may not even be possible currently based on adjacent logic that has some strong opinions about the possible set of GrantTypes:

```python
        GrantTypeClass: Type[
            Union[
                GrantTypeBase[TRequest, TStorage],
                AuthorizationCodeGrantType[TRequest, TStorage],
                PasswordGrantType[TRequest, TStorage],
                RefreshTokenGrantType[TRequest, TStorage],
                ClientCredentialsGrantType[TRequest, TStorage],
            ]
        ]
```

Which is all to say that maybe it's not a problem to hardcode a check of `request.post.grant_type == "client_credentials"`.

Feedback welcome!

2023-03-20 17:58 UTC, tdg5 commented
Still trying to wrap my head around what is expected here... The [RFC says](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3):

> If the client type is confidential or the client was issued client credentials (or assigned other authentication requirements), the client MUST authenticate with the authorization server as described in Section 3.2.1.
> https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3

So I guess one important thing to callout there is the **if**. I don't believe there is any requirement that a client must be issued client credentials, so a client that is allowed to use only the `authorization_code` grant type should not need to provide `client_secret` as part of a `token` request. The existence of browser-based OAuth flows seems like it should make this point obvious because a browser has no privacy with which to utilize a `client_secret`.

All this certainly argues that the code I've proposed needs work. Looking down that road, it argues to me that `Client.client_secret` should be `Optional[str]` instead of `str` (though, frankly, I think it really ought to be `List[str]`, but that's a different discussion, I'd think), and I imagine things get messier from there.

Let me know how you would like to proceed and we can take it from there 😀

2023-03-20 18:02 UTC, tdg5 commented
One of the implementation options from the RFC related to Browser Based Apps is specific in pointing out that no secret is required or possible for the given implementation option:

> This application is considered a public client, since there is no way to issue it a client secret in this model.
> https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#section-6.4-3

2023-03-20 18:28 UTC, tdg5 commented on aioauth/server.py
> +            client_id = request.post.client_id
This is inadequate since the `client_id` could be in the auth headers.

2023-03-20 19:19 UTC, aliev commented
> I made this other branch that takes a more robust approach to solving the problem, but was struggling to fix the test failure it introduces: https://github.com/aliev/aioauth/compare/master...tdg5:aioauth:dannyg/other-approach?expand=1
> 
> If something more like that is preferable, I can update this PR with the code from that branch.
> 
> Specifically, I was struggling to get `tests/test_flow.py:368 test_client_credentials_flow_post_data` to pass because it seems the tests expect all requests to work the same as far as `client_secret` is concerned and the change in that branch makes it so a missing `client_secret` can still result in a successful request.

I think the first implementation with `if` condition was good, it's more explicit and can be easily documented with resources:

```python
        client_secret: Optional[str] = None

        if request.post.grant_type in ("client_credentials", "password", ):
            # client_secret is only expected for client_credentials, password grant types
            # https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
            # https://www.oauth.com/oauth2-servers/access-tokens/password-grant/
            client_id, client_secret = self.get_client_credentials(request)
        else:
            client_id = request.post.client_id
```

2023-03-20 20:28 UTC, tdg5 commented
@alilev I think this is ready for another look

2023-03-20 21:43 UTC, aliev requested changes
Looks good, few minor things are left.

2023-03-20 21:43 UTC, aliev commented on aioauth/grant_type.py
> +            raise InvalidClientError(request, "")
the same here:

```suggestion
            raise InvalidClientError[TRequest](request)
```

2023-03-20 21:43 UTC, aliev commented on aioauth/grant_type.py
> +            raise InvalidClientError(request, "")
second argument (description) is not needed here, also `TRequest` type is required here:

```suggestion
            raise InvalidClientError[TRequest](request)
```

2023-03-20 21:43 UTC, aliev commented on tests/test_flow.py
> +    print(f"client_id: {client_id}", flush=True)
can be removed.

2023-03-20 22:28 UTC, tdg5 commented
@aliev sorry about that, I've made the corrections you requested :+1:

2023-03-20 22:30 UTC, aliev approved these changes
looks great! approved :)

2023-03-20 22:37 UTC, merged

2023-03-21 07:28 UTC, aliev commented
@tdg5 I created new release based on these changes.

2023-03-21 11:14 UTC, tdg5 commented
Thanks @aliev! I apologize in advance for fretting over decisions made, but do you think we made the right choice for handling the password grant type? The spec seems pretty clear that `client_secret` is not a requirement for the password grant:

> If the client type is confidential or the client was issued client credentials (or assigned other authentication requirements), the client MUST authenticate with the authorization server as described in [Section 3.2.1](https://www.rfc-editor.org/rfc/rfc6749#section-3.2.1).

More from the spec about the design intent of the password grant type further supports the notion that a `client_secret` should be optional, otherwise some of the migrations they mention wouldn't be possible because a `client_secret` couldn't be properly secured:

> This grant type is suitable for clients capable of obtaining the resource owner's credentials (username and password, typically using an interactive form).  It is also used to migrate existing clients using direct authentication schemes such as HTTP Basic or Digest authentication to OAuth by converting the stored credentials to an access token.
> https://www.rfc-editor.org/rfc/rfc6749#section-4.3

To be clear, I don't love the password grant and I am aware that:

1. [Current best practices recommend not using the password grant type at all](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-resource-owner-password-cre:~:text=The%20resource%20owner%20password%20credentials%20grant%20MUST%20NOT%20be%20used.)
2. [The password grant type is not included in the OAuth 2.1 spec](https://oauth.net/2.1/#:~:text=The%20Resource%20Owner%20Password%20Credentials%20grant%20is%20omitted%20from%20this%20specification)

but, that said, I could see the password grant (without requiring a `client_secret`) being useful for adoption of this library since it enables migrating less secure flows in the direction of more secure flows.

I guess that is all to say, I'm fine to neglect the password grant type since its days are numbered, but I'm willing to put some more time into making `client_secret` optional for the password grant type if you're open to that change.